
SOURCES = [
	'main.cpp',
	'FunctionParserTest.cpp',
	'TypeParserTest.cpp',
	'ClassParserTest.cpp',
	'NamespaceParserTest.cpp'
]


def build (bld):
	bld.program (
		source = SOURCES,
		includes = bld.env.GENERATOR_INCLUDES + [bld.top_dir + "/test/gtest"],
		target = "MyelinGenerateTest",
		use = ["gtest", "MyelinGenerator", "CTEMPLATE"],
	)


def test (ctx):
	# use subprocess instead of waf rules so we can get the pretty shell colours
	import subprocess
	subprocess.call([ctx.path.get_bld().abspath() + "/MyelinGenerateTest"])